workspace:
  base: /drone
  path: src/
pipeline:
  build:
    image: neunnsy/maven3-jdk-7:v1.0.0
    commands:
      - mvn package
      - mvn site
      - mvn cobertura:cobertura
      - mvn checkstyle:checkstyle
      - mvn jxr:jxr
    volumes:
      - /root/.m2:/root/.m2
  publish-master:
    image: neunnsy/docker:v0.0.1
    registry: index.neunn.com
    username: admin
    password: 12345678
    repo: index.neunn.com/library/webdemo
    tag: 0.1.${DRONE_BUILD_NUMBER}
    file: Dockerfile
    insecure: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    trusted: true
    when:
      branch: master
      status: [ success ]
  publish-dev:
    image: neunnsy/docker:v0.0.1
    registry: index.neunn.com
    username: admin
    password: 12345678
    repo: index.neunn.com/library/webdemo
    tag: 0.1.${DRONE_BUILD_NUMBER}
    file: Dockerfile
    insecure: false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    trusted: true
    when:
      branch: dev
      status: [ success ]
  kubernetes-master:
    image: vallard/drone-kube
    template: deployment.yml
    namespace: default
    secrets: [ KUBE_CA, KUBE_TOKEN, KUBE_SERVER ]
    when:
      branch: master
      status: [ success ]
  kubernetes-dev:
    image: vallard/drone-kube
    template: deployment.yml
    namespace: default
    secrets: [ KUBE_CA, KUBE_TOKEN, KUBE_SERVER ]
    when:
      branch: dev
      status: [ success ]
  notify:
    image: drillster/drone-email
    from: crazy_invoker@sina.com
    host: smtp.sina.com
    port: 25
    username: crazy_invoker
    password: woaiwenwen0708
    recipients:
      - zhaozy@neunn.com