apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cicd-webdemo
  labels:
    app: cicd-webdemo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cicd-webdemo
    spec:
      containers:
      - name: cicd-webdemo
        image: index.neunn.com/library/webdemo:0.1.{{ build.number }}
        ports:
        - containerPort: 8080